account/urls.py
from django.urls import path
from account.views import SignUpView, LoginView, LogoutView

app_name = 'account'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),

]

bookmyticket/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include("core.urls")),
                  path('', include("account.urls")),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from .views import HomeView,MovieDetail

app_name = "core"

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('movie/<int:pk>', MovieDetail.as_view(), name="movie_detail"),
]

account/models.py
from django.db import models

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    email_confirmed = models.BooleanField(default=False)


@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
        instance.profile.save()

core/models.py
from django.db import models
from multiselectfield import MultiSelectField


# Create your models here.

class Language(models.Model):
    language = models.CharField(max_length=150)

    def __str__(self):
        return self.language


class Movie(models.Model):
    TAG = (
        ("Drama", "Drama"),
        ("Comedy", "Comedy"),
        ("Action", "Action"),
        ("Animations", "Animations"),

    )
    TYPE = (
        ("2D", "2D"),
        ("3D", "3D")
    )
    name = models.CharField(max_length=150)
    image = models.ImageField(null=True, blank=True)
    banner = models.ImageField(null=True, blank=True)
    tags = MultiSelectField(
        choices=TAG, max_length=100, null=True, blank=True
    )
    release_date = models.DateField()
    type = MultiSelectField(
        choices=TYPE, max_length=100, null=True, blank=True
    )
    language = models.ManyToManyField(Language)
    recommended = models.BooleanField(default=False)
    duration = models.CharField(blank=True,null=True,max_length=100)
    movie_description = models.TextField(null=True,blank=True)

    def __str__(self):
        return self.name

account/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')


class UserLoginForm(forms.Form):
    """
        Used to manage custom Login form view
    """

    email = forms.EmailField(
        required=True,
        error_messages={
            'invalid': "Please enter a valid email address.",
            'required': "Please enter an email address."
        })
    password = forms.CharField(required=True,
                               error_messages={
                                   'required': "Please enter a password.",
                               }
                               )

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get("email")
        password = cleaned_data.get("password")

        if email and password:
            if not User.objects.filter(
                    email=email
            ).exists():
                raise ValidationError("User with this email is not exist.")

            user_obj = User.objects.get(
                email=email
            )
            if not user_obj.check_password(password):
                raise ValidationError("Please enter correct password.")
            if not user_obj.is_active:
                raise ValidationError(
                    "Your account is Inactive. Please check your registered "
                    "email for account activation.")
            # self.user = userprofile_obj.user
            return user_obj
        return self.cleaned_data

    def save(self, commit=True):
        user = super().save()

account/views.py
from django.contrib.auth.mixins import AccessMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import View, UpdateView, TemplateView, FormView
from .forms import SignUpForm, UserLoginForm
from django.contrib.auth.models import User

from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .token import account_activation_token

from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.utils.encoding import force_str


class LoginRequired(AccessMixin):
    """Verify that the current user is authenticated."""

    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect("account:login")
        return super().dispatch(request, *args, **kwargs)


class SignUpView(View):
    form_class = SignUpForm
    template_name = "account/login.html"

    def get(self, request, *args, **kwargs):
        return render(request, self.template_name)

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect("account:login")
        return render(request, self.template_name, {'form': form})


class LoginView(FormView):
    """
        Used to manage User Login view
    """
    form_class = UserLoginForm
    template_name = "account/login.html"

    def form_valid(self, form):
        user = form.cleaned_data
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        login(self.request, user)
        return redirect("core:home")

    def form_invalid(self, form):
        return super().form_invalid(form)


class LogoutView(FormView):
    """
        Used to manage User Logout View
    """

    def get(self, *args, **kwargs):
        logout(self.request)
        messages.success(self.request, "User logged out successfully.")
        return redirect("account:login")

core/views.py
from django.shortcuts import render
from django.views.generic import View, DetailView
from core.models import Movie
from account.views import LoginRequired


# Create your views here.
class HomeView(View):
    template_name = "core/home2.html"
    model_class = Movie

    def get(self, *args, **kwargs):
        movie = self.model_class.objects.all()
        context = {"movie": movie}
        return render(self.request, self.template_name, context=context)


class MovieDetail(DetailView):
    model = Movie
    template_name = "core/movie_detail.html"

    def get(self, *args, **kwargs):
        movie = Movie.objects.get(pk=self.kwargs.get("pk"))
        return render(self.request, self.template_name, context={"movie": movie})

templates/core/home.html
{% load static %}
<!DOCTYPE HTML>
<html>
	<head>
		<title>Book My Tickets</title>
		<link rel="stylesheet" type="text/css" href="{% static 'master/css/bootstrap.min.css' %}"/>
		<link rel="stylesheet" type="text/css" href="{% static 'master/css/bookShow.css' %}"/>
	</head>
	<body>
		<nav class="navbar navbar-default">
			<div class="container-fluid">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="#">Book My Tickets</a>
				</div>

				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav">
						<li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>
					</ul>

				</div><!-- /.navbar-collapse -->
			</div><!-- /.container-fluid -->
		</nav>




		<!--Ticket booking panel with dropdown for selecting movie,category and quantity-->
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-primary">
						<div class="panel-heading">
						<h3 class="panel-title">Book your tickets</h3>
						</div>
						<div class="panel-body">
							<form accept-charset="UTF-8" role="form">
								<fieldset>
									<div class="row">
               						<div class="col-md-4 col-xs-12 btn-group btn-input clearfix">
                 					<button type="button" class="btn btn-default movies-toggle dropdown-toggle form-control" data-toggle="dropdown">
                   					<span data-bind="label">Select Movie</span>&nbsp;<span class="caret"></span>
                 					</button>
                 					<ul class="movies dropdown-menu col-md-11 col-xs-11" role="menu">
                 					</ul>
               						</div>



									<div class="col-md-4 col-xs-12 btn-group btn-input clearfix">
                 					<button type="button" class="btn btn-default category-toggle dropdown-toggle form-control disabled" data-toggle="dropdown">
                   					<span data-bind="label">Select Category</span>&nbsp;<span class="caret"></span>
                 					</button>
                 					<ul class="movie_category dropdown-menu col-md-11 col-xs-11" role="menu">
                 					</ul>
               						</div>

               						<div class="col-md-4 col-xs-12 btn-group btn-input clearfix">
                 					<button type="button" class="btn btn-default quantity-toggle dropdown-toggle form-control disabled" data-toggle="dropdown">
                   					<span data-bind="label">Quantity</span>&nbsp;<span class="caret"></span>
                 					</button>
                 					<ul class="quantity dropdown-menu col-md-11 col-xs-11" role="menu">
                 					</ul>
               						</div>
               						</div>



               						<div class="row">
             						<div class="col-md-2 col-xs-12" style="float:right;">
									<input class="book col-xs-12 btn btn-md btn-success disabled" type="button" value="Book Tickets">
									</div>
									</div>


								</fieldset>
							</form>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="modal fade" id="myModal">
			<div class="modal-dialog">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<h4 class="modal-title"></h4>
					</div>
					<div class="modal-body">

					<div class="seats_alert alert alert-dismissible" role="alert">
  					<button type="button" class="close"><span aria-hidden="true">&times;</span></button>
  					<span></span>
					</div>
					<div class="book_alert alert alert-success alert-dismissible" role="alert">
  					<button type="button" class="close"><span aria-hidden="true">&times;</span></button>
  					<span></span>
					</div>

						<div class="main_container" id="container">

							<!--Inside here the seat map will be created by the js file-->
						</div>
					</div>
					<div class="modal-footer">

						<button type="button" class="btn btn-primary disabled checkout">Checkout</button>
					</div>
				</div><!-- /.modal-content -->
			</div><!-- /.modal-dialog -->
		</div><!-- /.modal -->

	</body>
<script type="text/javascript" src="{% static 'master/js/jquery.js' %}">
</script>
<script type="text/javascript" src="{% static 'master/js/bootstrap.js' %}">
</script>
<script type="text/javascript" src="{% static 'master/js/bookShow.js' %}">
</script>
</html>

templates/core/home2.html
{% load static %}
<!DOCTYPE HTML>
<html>
<head>
    <title>Book My Tickets</title>
    <link rel="stylesheet" type="text/css" href="{% static 'master/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'master/css/bookShow.css' %}"/>
</head>
<body style="background-color: #ffffff;color: black">
<nav class="navbar navbar-default" style="margin-bottom:0;border-radius: 5px">
    <div class="container-fluid" style="background-color: #192030;">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <img src="{% static 'core/images/logo2.png' %}" height="80px">
            {#            <a class="navbar-brand" href="#">Book My Tickets</a>#}
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        {#        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">#}
        {#            <ul class="nav navbar-nav">#}
        {#                <li class="active"><a href="#">Home <span class="sr-only">(current)</span></a></li>#}
        {#            </ul>#}
        {##}
        {#        </div><!-- /.navbar-collapse -->#}
    </div><!-- /.container-fluid -->
</nav>

<div class="sub_nav" style="height: 25px;background-color: #3b455e;margin-bottom: 5px;border-bottom-left-radius: 40px;border-bottom-right-radius: 40px"></div>

<div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        {% for image in movie %}
            {% if forloop.counter == 1 %}
                <div class="item active">
                    {% if image.banner %}
                        <img src="{{ image.banner.url }}">
                    {% else %}
                        <img src="{% static 'movie/images/no-image.png' %}" alt="Chania">
                    {% endif %}
                </div>
            {% else %}
                <div class="item">
                    {% if image.banner %}
                        <img src="{{ image.banner.url }}" alt="Chania">
                    {% else %}
                        <img src="{% static 'movie/images/no-image.png' %}" alt="Chania">
                    {% endif %}
                </div>
            {% endif %}


        {% endfor %}
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>


{% comment %}
---------------------- CARD VIEW FOR MOVIES----------------------------------------
{% endcomment %}
<div class="row" style="margin-left:55px ">
    {% for movie in movie %}
        <a href="{% url 'core:movie_detail' movie.pk %}" style="text-decoration: none;color: black">
        <div class="col-sm-6" style="margin-right: 40px;margin-left:40px;margin-top:20px;max-width: fit-content;width: fit-content">
            <div class="card">
                <div class="card-body">
                    <div style="display: flex;">
                        <div>
                            <img src="{% if not movie.image %}
                    {% static 'movie/images/no-image.png' %}
                    {% else %}{{ movie.image.url }}
                    {% endif %}" width="220" height="320" style="border-radius: 13px">
                        </div>
                    </div>
                    <div>
                        <h2 class="card-title">{{ movie.name}}</h2>
                        <h5 class="card-title">{{movie.tags}}</h5>
                    </div>
                </div>
            </div>
        </div>
    </a>
    {% endfor %}
</div>

</body>
<script type="text/javascript" src="{% static 'master/js/jquery.js' %}">
</script>
<script type="text/javascript" src="{% static 'master/js/bootstrap.js' %}">
</script>
<script type="text/javascript" src="{% static 'master/js/bookShow.js' %}">
</script>
</html>

templates/core/movie_detail.html
{% load static %}
<html>
<head>
    <title>Book My Tickets</title>
    <link rel="stylesheet" type="text/css" href="{% static 'master/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'master/css/bookShow.css' %}"/>

</head>
<body style="background-color: #ffffff;color: black">
<nav class="navbar navbar-default" style="margin-bottom: 0">
    <div class="container-fluid" style="background-color: #192030;">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <img src="{% static 'core/images/logo2.png' %}" height="80px">
        </div>
    </div>
</nav>
<div class="sub_nav"
     style="height: 25px;background-color: #3b455e;margin-bottom: 5px;border-bottom-left-radius: 40px;border-bottom-right-radius: 40px"></div>
{#-------------------------------------------------------------------------#}
{#             BANNER SECTION          #}
{#-------------------------------------------------------------------------#}
<section class="sc-qswwm9-0 ljnioe">
    <div class="sc-qswwm9-1 eQtXbA"
         style="background-image: linear-gradient(90deg, rgb(26, 26, 26) 24.97%,
                 rgb(26, 26, 26) 38.3%, rgba(26, 26, 26, 0.04) 97.47%, rgb(26, 26, 26) 100%),
                 url({{ movie.banner.url }});height: 500px">
        <div class="sc-qswwm9-2 cUDDgh">
            <div class="sc-qswwm9-4 eWuQcQ">
                <section class="sc-bsek5f-0 fSyllq" id="banner_data">
                    <div class="section_content">
                        <div type="vertical" class="sc-echj48-0 iCYiPJ">
                            <div class="sc-echj48-6 csqwyD"
                                 style="border-radius: 16px 16px 0px 0px; object-fit: cover;">
                                <img src="{{ movie.image.url }}" width="320px" height="440px" class="sc-echj48-5 hutamn"
                                     style="border-radius: 16px 16px 0px 0px; object-fit: cover;"></div>
                        </div>
                        <div class="inner-data">
                            <h3 style="color:white;font-weight: bolder;font-size: 50px">{{ movie.name }}</h3>

                            <div class="sc-2k6tnd-0 ddXVHR">
                                <div class="sc-2k6tnd-1 btqyFP">
                                    <div class="sc-2k6tnd-4 fdHSZD">{{ movie.type }}</div>
                                    <div class="sc-2k6tnd-4 fdHSZD">
                                        {% for i in movie.language.values %}
                                            {{ i.language }},
                                        {% endfor %}
                                    </div>
                                </div>
                                <div class="sc-2k6tnd-1 btqyFP">{{ movie.duration }}
                                    <span class="sc-2k6tnd-5 kvkTzz">  •  </span>
                                    {% for tag in movie.tags %}
                                        <span class="sc-2k6tnd-2 ijNbsp">{{ tag }},</span>
                                    {% endfor %}
                                    <span class="sc-2k6tnd-5 kvkTzz">  •  </span>
                                    UA
                                    <span class="sc-2k6tnd-5 kvkTzz">  •  </span>
                                    {{ movie.release_date }}
                                </div>
                            </div>
                        </div>
                    </div>
                </section>

            </div>
        </div>
    </div>
</section>

{#-------------------------------------------------------------------------#}
{#             ABOUT MOVIE          #}
{#-------------------------------------------------------------------------#}

<div class="container">
    <div class="title">
        <h3 style="font-size: 35px;font-weight: bold">
            About the movie
        </h3>
    </div>
    <div class="content" style="margin-bottom: 20px">
        <p>
            {{ movie.movie_description }}
        </p>
    </div>
    <hr>
</div>

{#-------------------------------------------------------------------------#}
{#            BOOK TIKCETS BUTTON          #}
{#-------------------------------------------------------------------------#}

<div class="book_ticket_button" style="
    width: 100%;
    display: flex;
    justify-content: center;">
    <button onclick="show_div()" class="btn" type="button" style="
    color:#ffffff;
    background-color: rgb(247,68,101);
    font-size: 25px;
    border-radius: 10px;
    width: 200px;
    ">
        Book Tickets
    </button>

</div>


{#-------------------------------------------------------------------------#}
{#            BOOK TIKCETS DIV         #}
{#-------------------------------------------------------------------------#}

<div class="container" id="bookticketdiv" style="display: none">
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary" style="border-radius: 15px">
                <div class="panel-heading" id="book-ticket-heading" style="border-radius: 15px">
                    <h3 class="panel-title">Book your tickets</h3>
                </div>
                <div class="panel-body" id="book-ticket-body">
                    <form accept-charset="UTF-8" role="form">
                        <fieldset>
                            <div class="row">
                                <div class="col-md-4 col-xs-12 btn-group btn-input clearfix">
                                    <button type="button"
                                            class="btn btn-default movies-toggle dropdown-toggle form-control"
                                            data-toggle="dropdown">
                                        <span data-bind="label">Select Movie</span>&nbsp;<span class="caret"></span>
                                    </button>
                                    <ul class="movies dropdown-menu col-md-11 col-xs-11" role="menu">
                                    </ul>
                                </div>


                                <div class="col-md-4 col-xs-12 btn-group btn-input clearfix">
                                    <button type="button"
                                            class="btn btn-default category-toggle dropdown-toggle form-control disabled"
                                            data-toggle="dropdown">
                                        <span data-bind="label">Select Category</span>&nbsp;<span class="caret"></span>
                                    </button>
                                    <ul class="movie_category dropdown-menu col-md-11 col-xs-11" role="menu">
                                    </ul>
                                </div>

                                <div class="col-md-4 col-xs-12 btn-group btn-input clearfix">
                                    <button type="button"
                                            class="btn btn-default quantity-toggle dropdown-toggle form-control disabled"
                                            data-toggle="dropdown">
                                        <span data-bind="label">Quantity</span>&nbsp;<span class="caret"></span>
                                    </button>
                                    <ul class="quantity dropdown-menu col-md-11 col-xs-11" role="menu">
                                    </ul>
                                </div>
                            </div>


                            <div class="row">
                                <div class="col-md-2 col-xs-12" style="float:right;">
                                    <input class="book col-xs-12 btn btn-md btn-success" type="button"
                                           value="Book Tickets" data-toggle="modal" data-target="#exampleModalCenter2">
                                </div>
                            </div>
                        </fieldset>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{#---------------------------SEFL MADE MODAL-------------------------------------------#}
<div class="modal fade" id="exampleModalCenter2" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>


{#-------------------------------------------READY MADE DIV-------------------------------------#}
{% comment %}
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">

                <div class="seats_alert alert alert-dismissible" role="alert">
                    <button type="button" class="close"><span aria-hidden="true">&times;</span></button>
                    <span></span>
                </div>
                <div class="book_alert alert alert-success alert-dismissible" role="alert">
                    <button type="button" class="close"><span aria-hidden="true">&times;</span></button>
                    <span></span>
                </div>

                <div class="main_con
                tainer" id="container">

                    <!--Inside here the seat map will be created by the js file-->
                </div>
            </div>
            <div class="modal-footer">

                <button type="button" class="btn btn-primary disabled checkout">Checkout</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% endcomment %}
</body>
<script>
    function show_div() {
        var x = document.getElementById("bookticketdiv");
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>
<script type="text/javascript" src="{% static 'master/js/jquery.js' %}">
</script>
<script type="text/javascript" src="{% static 'master/js/bootstrap.js' %}">
</script>
<script type="text/javascript" src="{% static 'master/js/bookShow.js' %}">
</script>